[package]
name = "ping_pong_bot"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition = "2018"

[dependencies]
telexide_fork = { path = "../../" }
tokio = { version = "1", features = ["full"] }
