[package]
name = "repeat_image_bot"
version = "0.1.0"
authors = ["my name <my@email.address>"]
edition = "2018"

[dependencies]
telexide_fork = { path = "../../" }
tokio = { version = "1", features = ["full"] }
env_logger = "0.7"
log = "0.4"
